[build]
publish = "dist"
command = "pnpm run generate"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# Fallback
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
NODE_VERSION = "23.7"
